### ISSUE TITLE
Это всё логотип 

### ISSUE THREAD

**Issue by basharinandrej** [basharinandre/learning#2]
https://github.com/basharinandre/learning/blob/284f1b63007cbed2541f0925705f31b1ea3c4902/index.html#L11-L12

Нужно обернуть в ссылку и добавить помимо class="logo", class="header__logo" - элемент

**Comment by dem1dov1van** [comment]
Сделал. Ссылке дал класс logo__homeLink (сначала хотел без Home)

**Comment by basharinandrej** [comment]
CamelCase не подходит по БЭМ

**Comment by dem1dov1van** [comment]
Я вот перечитываю это, и как у тебя ещё не горит? Столько раз по одному и тому-же)
