### ISSUE TITLE
Это элемент

### ISSUE THREAD

**Issue by basharinandrej** [basharinandre/learning#21]
https://github.com/basharinandre/learning/blob/b435a624e6adb8c694d8ea34ad57b13d956ee4e3/index.html#L122-L127

ты сделал элементом class="caption__text" - два нижних __ это элемент

**Comment by dem1dov1van** [comment]
Ну ты понял(блок)

**Comment by basharinandrej** [comment]
Некорректный класс для элемента, нет наследования от блока

**Comment by dem1dov1van** [comment]
Исправил
