### ISSUE TITLE
caption vs title

### ISSUE THREAD

**Issue by basharinandrej** [basharinandre/learning#26]
https://github.com/basharinandre/learning/blob/b435a624e6adb8c694d8ea34ad57b13d956ee4e3/index.html#L208

у тебя в разных секциях у одного и того же заголовка разные классы. Определись с одним

**Comment by dem1dov1van** [comment]
Не помню - исправил или нет, но  для маленького заголовка с прозрачностью я применил класс tagline
Для заголовка здорового человека - caption

**Comment by dem1dov1van** [comment]
Да, title на caption поменял
