### ISSUE TITLE
Почему class="offer"

### ISSUE THREAD

**Issue by basharinandrej** [basharinandre/learning#3]
https://github.com/basharinandre/learning/blob/284f1b63007cbed2541f0925705f31b1ea3c4902/index.html#L13-L30

 - По смыслу offer - это уникальное торговое предложение (УТП)
    Здесь я бы использовал просто class="main-list" - чтобы можно было переиспользовать этот список 
    
- и вместо div, нужен ul

**Comment by dem1dov1van** [comment]
Мужик, честное слово, всегда был уверен, что offer переводится как "обёртка". Только что глянул перевод...
Мне кажется есть смысл телефон обернуть в ссылку для мобилок, но это если будет мобильная версия, здесь её нет - фиг вам а не ссылка(согласен?)
Как по-твоему, правильная ли конструкция в header__logo logo(что картинка в ссылке, а ссылка в диве)?

**Comment by basharinandrej** [comment]
Да, телефон нужно обернуть в ссылку. <a href="tel:89815095219"> 89815095219 </a>

В этом фрагменте кода я не нашёл header__logo, наверно из другого бага ?
Если  header__logo не отсюда, то переводи баг обратно на меня я его закрою
