### ISSUE TITLE
 BuhOne вынести в ссылку

### ISSUE THREAD

**Issue by basharinandrej** [basharinandre/learning#30]
https://github.com/basharinandre/learning/blob/b435a624e6adb8c694d8ea34ad57b13d956ee4e3/index.html#L241
слово  BuhOne  вынести в ссылку

**Comment by dem1dov1van** [comment]
В таких случаях целесообразно в классе прописывать куда она ведёт?
Например: class = 'footer__home-link'; или link'ом обойтись?
