### ISSUE TITLE
Некорректное название трёх элементов

### ISSUE THREAD

**Issue by basharinandrej** [basharinandre/learning#34]
https://github.com/basharinandre/learning/blob/f38586f44aa43257f68af9c4d376baff27306e0d/index.html#L73-L76

slide__main-wrap, slide__title, slide__button

**slider__main-wrap, slider__title, slider__button** - такие, либо вернуть блок для одно слайда

**Comment by dem1dov1van** [comment]
Погоди, правильно ли я понимаю, что если (например у div'а) нет блока, то мы его игнорируем, и его элемент дочерний элемент создаём с названием родителя этого div'a(конечно, если у родителя есть блок)?
