### ISSUE TITLE
Телефон всегда <a>

### ISSUE THREAD

**Issue by basharinandrej** [basharinandre/learning#4]
https://github.com/basharinandre/learning/blob/284f1b63007cbed2541f0925705f31b1ea3c4902/index.html#L16

и нужно добавить, в ссылку такой атрибут, чтобы можно было звонить по клику на ссылку href="tel:89815095219".

**Comment by dem1dov1van** [comment]
Из предыдущего про тлф можешь не отвечать))
Нужно в классе для ссылки указывать, что это ссылка (link)?
Также сделал всё это ссылками - при оформлении их можно сделать неактивными/добавлять какие-то фичи(по типу открытия гугл карт по нажатию на адрес и тд...)
