### ISSUE TITLE
блок item скорее всего не нужен, или поясни для чего

### ISSUE THREAD

**Issue by basharinandrej** [basharinandre/learning#5]
https://github.com/basharinandre/learning/blob/284f1b63007cbed2541f0925705f31b1ea3c4902/index.html#L14-L17

class="item" - скорее всего не нужен, ведь если ты будешь переиспользовать даже один элемент ты можешь копировать весь список, но в нём будет один элемент

**Comment by dem1dov1van** [comment]
Ничего, что мы будем использовать для дочерних <img> и <a>(здесь еще <p>) class="item__icon-clock", то есть указывая, что картинка лежит в блоке item, а блока item нет, есть только элемент main-list__item?

**Comment by basharinandrej** [comment]
у списков я обычно использую следующую систему наименования классов
ul class="main-alist"
--li class="main-alist__item"
----img class="main-alist__img 
      ----   p class="main-alist__paragraph 
         
Можно не использовать блок item, а использовать main-alist. Потому что делать блоком один элемент li, бессмысленно, 
ведь просто li, без ul ты использовать не будешь

**Comment by Dem1dov1van** [comment]
Дадада, я его убирал, но сегодня утром добавил по тупости, sorry
