### ISSUE TITLE
тег <nav>

### ISSUE THREAD

**Issue by basharinandrej** [basharinandre/learning#6]
https://github.com/basharinandre/learning/blob/284f1b63007cbed2541f0925705f31b1ea3c4902/index.html#L31-L46

вместо div, тег nav

**Comment by dem1dov1van** [comment]
Здесь напрашивается использование предыдущего списка(class="header__main-list main-list"), но шрифты другие, надеюсь это будет легко исправимо. 
И будет ли корректно использовать ещё один class="main-list"?

**Comment by basharinandrej** [comment]
Есть несколько вариантов 
1) Добавить модификатор на main-list main-list--navigation и уже для него прописывать новые стили связанные со шрифтами
2) Идти от main-navigation по вложенности, но так будет повышаться специфичность 
.main-navigation .main-list__item {
style
}
3) Либо придумать новый список 
4) Cамый (как мне кажется адекватный способ) это сделать  main-navigation блоком, тег ul это уже элемент с классом  main-navigation__alist, li - также элемент  main-navigation__item и так далее

**Comment by dem1dov1van** [comment]
Andy, разве li это main-navigation__item? По вложенности он должен быть list__item, не?
