### ISSUE TITLE
camelCase по БЭМ'у не подходит 

### ISSUE THREAD

**Issue by basharinandrej** [basharinandre/learning#7]
https://github.com/basharinandre/learning/blob/284f1b63007cbed2541f0925705f31b1ea3c4902/index.html#L48

по БЭМ'у
- блок это тире (-)
- элемент это два нижних ( __ )
- модификатор это два тире ( -- )

class="section-hero"

**Comment by dem1dov1van** [comment]
Js отдельно - html отдельно...
Понял принял

**Comment by dem1dov1van** [comment]
Даже abousUs через тире? Так class="header__section-about-us section-about-us"?

**Comment by basharinandrej** [comment]
Просто header__section-about, и так будет понятно. Чем короче тем чище
