### ISSUE TITLE
почему section-hero

### ISSUE THREAD

**Issue by basharinandrej** [basharinandre/learning#8]
https://github.com/basharinandre/learning/blob/284f1b63007cbed2541f0925705f31b1ea3c4902/index.html#L48

почему section-hero ? Вот тут как раз подходит class="section-offer".

Хотя, я бы даже не выносил это в отдельный тег section, а положил бы всё в тег header и добавил бы класс class="main-offer"

**Comment by dem1dov1van** [comment]
Счас объясню. В css-книге был пример с аналогичным изображением и там картинка классифицировалась как hero-img. Поэтому у меня сложился стереотип, что такие картинки во всю страницы называются "хероу-иэмджи"
Сейчас, когда я узнал перевод offer - с тобой полностью согласен, что это "главное предложение"
